### PR TITLE
feat(tier4_control_rviz_plugin): change to read topic by polling and add missing subscriber

### PR DESCRIPTION
**Pull request by Autumn60**
## Description

Based on [the discussion](https://github.com/orgs/autowarefoundation/discussions/4612), change `tier4_control_rviz_plugin` to read topic by polling instead of best_effort callback.

and

Add missing subscriber for `geometry_msgs::msg::AccelWithCovarianceStamped`

## Related links

https://github.com/orgs/autowarefoundation/discussions/4612

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by maxime-clem — APPROVED** [review]

**Comment by xmfcx** [comment]
I've fixed the CI issue with the build-and-test-differential workflow:
- https://github.com/autowarefoundation/autoware_tools/pull/55

So I'm updating this to `main` branch.

`build-and-test-differential` workflow should now work as expected.

Also the codeowners are updated, at least one approval from them is required.

If you are experienced in this package, you may add yourself to package maintainer list too.

**Comment by Autumn60** [comment]
I will wait a bit to merge this PR as I expect build failures due to changes in https://github.com/autowarefoundation/autoware.universe/pull/7538.

@xmfcx 
Thank you for fixing the build-and-test-diff CI.
Also, I will add myself to the package maintainer with your suggestion. :pray:

**Comment by Autumn60** [comment]
@taikitanaka3 
Could you review this PR as a code owner?

**Review by taikitanaka3 — APPROVED** [review]

**Comment by Autumn60** [comment]
waiting for https://github.com/autowarefoundation/autoware_tools/pull/59 to be merged

**Pull request merged**
