### PR TITLE
refactor(glog_component): prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by esteve**
## Related links

https://github.com/autowarefoundation/autoware.universe/pull/9302
https://github.com/autowarefoundation/autoware/issues/5077
https://github.com/autowarefoundation/autoware/issues/4569

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by go-sakayori — APPROVED** [review]

**Comment by xmfcx** [comment]
This was supposed to be merged along with others:
- https://github.com/autowarefoundation/autoware.universe/pull/9302#issuecomment-2488505701

Was merged due to auto-merge.

**Comment by esteve** [comment]
@xmfcx oh, sorry, shall I submit a PR to revert these changes?

**Comment by esteve** [comment]
@xmfcx I've disabled auto-merge from the other PRs to prevent this happening again.

**Comment by xmfcx** [comment]
> shall I submit a PR to revert these changes?

For now it's 🆗 since I am actively going to try to merge the others, compiling with everything checked out right now.

image

**Pull request merged**
