### PR TITLE
fix(driving_environment_analyzer): remove unused autoware_interpolation dependency

### PR DESCRIPTION
**Pull request by xmfcx**
## Description

Follow up from:
- https://github.com/autowarefoundation/autoware.universe/pull/8088

There is no mention of the word "interpolation" within this package directory. I have doubts that this package uses this dependency.

## Notes for reviewers

:rotating_light: :warning: Must be merged after:
- https://github.com/autowarefoundation/autoware.universe/pull/8088

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
image

There is no mention of the word "interpolation" within this package directory. I have doubts that this package uses this dependency.

@satoshi-ota could you check if this package makes use of this dependency?

**Comment by xmfcx** [comment]
I've renamed this pr, removing this dependency, I don't think it's used. None of the headers are directly referenced from that package.

**Comment by xmfcx** [comment]
@satoshi-ota -san, could you review?

**Comment by xmfcx** [comment]
@satoshi-ota -san could you review please? It's a small PR.

**Review by esteve — APPROVED** [review]
@xmfcx thanks!

**Pull request merged**
