### PR TITLE
refactor(path_optimizer): rename package name and fix trajectory visualizer

### PR DESCRIPTION
**Pull request by kosuke55**
## Description

obstacle_avoidance_planner -> path_optimizer

related to:
https://github.com/orgs/autowarefoundation/discussions/4741

fix some tools to work

image

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kosuke55** [comment]
@takayuki5168 
could you please approve this PR?

**Review by takayuki5168 — APPROVED** [review]

**Comment by kosuke55** [comment]
@TakaHoribe @satoshi-ota please approve

**Comment by kosuke55** [comment]
@sasakisasaki 
thanks! but this PR is for rename of path_optimizer, so I would like to it as it is.

**Review by yhisaki — COMMENTED** [review]
```
        if self.update_traj_final:
            self.im10.set_data([0], [self.localization_vx])
            self.im11.set_data([0], [self.vehicle_vx])
```

**Review by satoshi-ota — APPROVED** [review]

**Pull request merged**
