### PR TITLE
feat: add vehicle, control and localization calibration tools

### PR DESCRIPTION
**Pull request by yabuta**
## Description

I move vehicle, control and localization calibration tools from CalibrationTools repojitory in TIER IV space.([discussion](https://github.com/tier4/CalibrationTools/discussions/157))

[CalibrationTools repojitory PR](https://github.com/tier4/CalibrationTools/pull/162)

I checked colconb build is success and tools launch test.
While stop_accel_evaluator is mentenance now, only build check

```
deviation_estimator: OK
stop_accel_evaluator: COLCON IGNORE
vehicle_cmd_analyzer: OK
parameter_estimator: OK
pitch_checker: OK
time_delay_estimator: OK
```

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by SakodaShintaro — APPROVED** [review]
Looks Good To Me

**Comment by SakodaShintaro** [comment]
Oh, some CI checks are failed.
It doesn't seem to be related to Localization, but I'll check again once it's fixed.

**Comment by yabuta** [comment]
@SakodaShintaro 
In pre-commit, there are errors in deviation_evaluator.
Pre-commit say it needs space after ':', is it OK to add space?

```
localization/deviation_estimation_tools/deviation_evaluator/scripts/deviation_evaluation_visualizer.py:46:46: E231 missing whitespace after ':'
            f"No error larger than {threshold:.3f} [m] observed. Provide more data on deviation_evaluator."
                                             ^
localization/deviation_estimation_tools/deviation_evaluator/scripts/deviation_evaluation_visualizer.py:55:48: E231 missing whitespace after ':'
        print(f"  [OK] lowerbound = {lowerbound:.3f} < {threshold:.3f} = threshold [m]")
                                               ^
localization/deviation_estimation_tools/deviation_evaluator/scripts/deviation_evaluation_visualizer.py:55:66: E231 missing whitespace after ':'
        print(f"  [OK] lowerbound = {lowerbound:.3f} < {threshold:.3f} = threshold [m]")
                                                                 ^
localization/deviation_estimation_tools/deviation_evaluator/scripts/deviation_evaluation_visualizer.py:57:48: E231 missing whitespace after ':'
        print(f"  [NG] lowerbound = {lowerbound:.3f} > {threshold:.3f} = threshold [m]")
                                               ^
localization/deviation_estimation_tools/deviation_evaluator/scripts/deviation_evaluation_visualizer.py:57:66: E231 missing whitespace after ':'
        print(f"  [NG] lowerbound = {lowerbound:.3f} > {threshold:.3f} = threshold [m]")
                                                                 ^
localization/deviation_estimation_tools/deviation_evaluator/scripts/deviation_evaluation_visualizer.py:62:40: E231 missing whitespace after ':'
        print(f"  [OK] recall = {recall:.3f} > {recall_threshold:.3f}")
                                       ^
localization/deviation_estimation_tools/deviation_evaluator/scripts/deviation_evaluation_visualizer.py:62:65: E231 missing whitespace after ':'
        print(f"  [OK] recall = {recall:.3f} > {recall_threshold:.3f}")
                                                                ^
localization/deviation_estimation_tools/deviation_evaluator/scripts/deviation_evaluation_visualizer.py:64:40: E231 missing whitespace after ':'
        print(f"  [NG] recall = {recall:.3f} < {recall_threshold:.3f}")
                                       ^
localization/deviation_estimation_tools/deviation_evaluator/scripts/deviation_evaluation_visualizer.py:64:65: E231 missing whitespace after ':'
        print(f"  [NG] recall = {recall:.3f} < {recall_threshold:.3f}")
                                                                ^
planning/planning_debug_tools/scripts/perception_replayer/utils.py:149:51: E231 missing whitespace after ':'
            print(f"Time for {name}: {elapsed_time:.2f} ms")
                                                  ^
10    E231 missing whitespace after ':'
```

**Comment by SakodaShintaro** [comment]
@yabuta 
It's a little strange that the linter gives a warning for ':' in a string.
I had the same problem before, and it was a bug in flake8, so when I updated the version, the warning disappeared.

https://github.com/autowarefoundation/autoware_launch/issues/970

**Comment by SakodaShintaro** [comment]
@yabuta 
I think this pull request will fix it. If this doesn't fix it, I'll change the code.
https://github.com/autowarefoundation/autoware_tools/pull/24

**Comment by yabuta** [comment]
@SakodaShintaro 
In other hand, spell check error occurs in deviation_evaluator and others.
 In deviation_evaluator, error words is minoda, koji and covs.Can you help to fix this error?

(Why ROS2 is error... )

**Comment by SakodaShintaro** [comment]
@yabuta 
I made a pull request to fix the localization part. The merge destination is this branch.
https://github.com/autowarefoundation/autoware_tools/pull/25

**Comment by yabuta** [comment]
@mitsudome-r Please approve if you look OK.

**Comment by SakodaShintaro** [comment]
What is the status of this pull request?

Also, I noticed that some packages use `autoware_auto_control_msgs::msg::AckermannControlCommand`, `autoware_auto_vehicle_msgs::msg::VelocityReport` , ... etc.
Should this pull request be merged and then fixed in another pull request?

**Comment by yabuta** [comment]
@SakodaShintaro I created [changing  msgs PR](https://github.com/autowarefoundation/autoware_tools/pull/42).
After changing msgs PR is merged this branch, I want to merge this PR to main.

**Comment by SakodaShintaro** [comment]
@yabuta 
Thank you very much.
I'm not in a hurry so I'll wait :+1:

**Comment by yabuta** [comment]
@SakodaShintaro I create PR. Please check deviation_estimator.
https://github.com/autowarefoundation/autoware_tools/pull/42

**Pull request merged**
